/** Shared scene keys — single source of truth for scene transitions. */
export const SceneKeys = {
  Boot: "boot",
  Preloader: "preloader",
  Overworld: "overworld",
} as const;

/** Shared placeholder texture keys, generated by PreloaderScene. */
export const TextureKeys = {
  TileGrass: "tileset-grass",
  TileWater: "tileset-water",
  TilePath: "tileset-path",
  PlayerIdleDown: "player-idle-down",
} as const;
