/** Shared scene keys — single source of truth for scene transitions. */
export const SceneKeys = {
  Boot: "boot",
  Preloader: "preloader",
  Overworld: "overworld",
} as const;

/** World zones (Phase 2): keys match design/world-map.md zone ids. */
export const ZoneKeys = {
  PostOffice: "zone-post-office",
  Bramble: "zone-bramble-patch",
} as const;

/** Shared placeholder texture keys, generated by PreloaderScene. */
export const TextureKeys = {
  /** Single generated tileset sheet — tile frame index comes from src/game/Tiles.ts. */
  TilesetMain: "tileset-main",
  PlayerIdleDown: "player-idle-down",
  PlayerShadow: "player-shadow",
} as const;
