-- Retired static-content seed.
-- Happy Valley metadata lives in src/data/zones.json and maps, item definitions
-- live in src/data/items.json, and monster templates plus loot tables live in
-- src/data/monsters.json. The JSON catalogs are synchronized after migrations.
