-- Retired static-content seed.
-- Tutorial quests, parcels, rewards, and dialogue are authored in
-- src/data/quests.json and src/data/items.json. Migration 010 provides the
-- character_quest_progress state boundary for existing installations.
