import { describe, expect, it } from "vitest";
import {
  computeStats,
  generateMeadow,
  generatePlaza,
  generateRoad,
  generateValleyMeadow,
  generateValleyPath,
} from "../../scripts/lib/ground-art.mjs";

/**
 * Regression pins for the Clover Village ground surfaces (generated by
 * scripts/generate-ground-assets.mjs via the shared scripts/lib/ground-art.mjs).
 *
 * The generator is deterministic, so these pins are stable. They exist so a
 * future tweak to the tone constants (targetL, the 0.72 saturation factor,
 * the mottling/stroke seeds, the road blotch-strip) cannot silently drift the
 * look the audit signed off on: calm pastel grass, not the original's dark
 * murky smear and not neon; a warm road with no repeating blotch; and tiles
 * whose wrap seam is no worse than the texture's own internal variation.
 *
 * Deliberate retunes must update the pinned expectations here in the same
 * change — that is the point of the test.
 */

const near = (actual: number, expected: number, tolerance: number) =>
  Math.abs(actual - expected) <= tolerance;

const meadow = generateMeadow();
const road = generateRoad();
const valleyMeadow = generateValleyMeadow();
const valleyPath = generateValleyPath();
const plaza = generatePlaza();
const meadowStats = computeStats(meadow.w, meadow.h, meadow.px);
const roadStats = computeStats(road.w, road.h, road.px);
const valleyMeadowStats = computeStats(valleyMeadow.w, valleyMeadow.h, valleyMeadow.px);
const valleyPathStats = computeStats(valleyPath.w, valleyPath.h, valleyPath.px);
const plazaStats = computeStats(plaza.w, plaza.h, plaza.px);

describe("ground art generator regression", () => {    it("is deterministic — same seeds produce identical pixels", () => {
    expect(Buffer.compare(meadow.px, generateMeadow().px)).toBe(0);
    expect(Buffer.compare(road.px, generateRoad().px)).toBe(0);
    expect(Buffer.compare(valleyMeadow.px, generateValleyMeadow().px)).toBe(0);
    expect(Buffer.compare(valleyPath.px, generateValleyPath().px)).toBe(0);
    expect(Buffer.compare(plaza.px, generatePlaza().px)).toBe(0);
  });

  describe("meadow tone (pack-pastel, not murky, not neon)", () => {
    it("keeps the signed-off palette average (110, 169, 72)", () => {
      expect(near(meadowStats.avgRGB.r, 110.3, 1.5)).toBe(true);
      expect(near(meadowStats.avgRGB.g, 169.2, 1.5)).toBe(true);
      expect(near(meadowStats.avgRGB.b, 71.8, 1.5)).toBe(true);
    });

    it("stays inside the pastel saturation band (0.72x source, ~0.42)", () => {
      expect(meadowStats.avgHsl.s).toBeGreaterThan(0.36);
      expect(meadowStats.avgHsl.s).toBeLessThan(0.46);
    });

    it("stays grass-family hue (~96deg) and mid-lightness (~0.47)", () => {
      expect(meadowStats.avgHsl.h).toBeGreaterThan(0.24);
      expect(meadowStats.avgHsl.h).toBeLessThan(0.29);
      expect(near(meadowStats.avgHsl.l, 0.472, 0.02)).toBe(true);
    });

    it("does not regress to the original's dark murky smear", () => {
      // land_1 before: lum mean 0.431, 24.4% of pixels darker than 0.4.
      expect(meadowStats.lumMean).toBeGreaterThan(0.52);
      expect(meadowStats.darkFraction).toBeLessThan(0.02);
    });

    it("wraps seamlessly — seam edges comparable to internal variation", () => {
      // Current: edgeLR 7.24, edgeTB 7.39 vs internal 3.44 (ratio ~2.1x).
      // A broken toroidal wrap pushes the seam well past these bounds.
      expect(meadowStats.edgeLR).toBeLessThan(12);
      expect(meadowStats.edgeTB).toBeLessThan(12);
      expect(meadowStats.edgeLR / meadowStats.internal).toBeLessThan(3.0);
      expect(meadowStats.edgeTB / meadowStats.internal).toBeLessThan(3.0);
    });
  });

  describe("road tone and seamlessness", () => {
    it("keeps the signed-off warm earth average (170, 123, 93)", () => {
      expect(near(roadStats.avgRGB.r, 170.2, 2)).toBe(true);
      expect(near(roadStats.avgRGB.g, 123.3, 2)).toBe(true);
      expect(near(roadStats.avgRGB.b, 92.8, 2)).toBe(true);
    });

    it("stays muted warm (no saturated blotch re-emerging)", () => {
      expect(roadStats.avgHsl.s).toBeGreaterThan(0.30);
      expect(roadStats.avgHsl.s).toBeLessThan(0.40);
    });

    it("wraps seamlessly — blotch stripping did not break tiling", () => {
      // Current: edgeLR 13.71, edgeTB 10.92 vs internal 8.74.
      expect(roadStats.edgeLR / roadStats.internal).toBeLessThan(2.2);
      expect(roadStats.edgeTB / roadStats.internal).toBeLessThan(1.8);
    });
  });

  describe("Happy Valley ground (same authored pipeline, valley palette)", () => {
    it("keeps the signed-off summer-meadow average (114, 170, 68)", () => {
      expect(near(valleyMeadowStats.avgRGB.r, 114.0, 1.5)).toBe(true);
      expect(near(valleyMeadowStats.avgRGB.g, 170.0, 1.5)).toBe(true);
      expect(near(valleyMeadowStats.avgRGB.b, 67.8, 1.5)).toBe(true);
    });

    it("stays in the pastel summer band (sat ~0.43, hue ~93deg)", () => {
      expect(valleyMeadowStats.avgHsl.s).toBeGreaterThan(0.38);
      expect(valleyMeadowStats.avgHsl.s).toBeLessThan(0.48);
      expect(valleyMeadowStats.avgHsl.h).toBeGreaterThan(0.24);
      expect(valleyMeadowStats.avgHsl.h).toBeLessThan(0.28);
      expect(near(valleyMeadowStats.avgHsl.l, 0.466, 0.02)).toBe(true);
    });

    it("is not a murky smear and wraps at parity with internal variation", () => {
      expect(valleyMeadowStats.lumMean).toBeGreaterThan(0.52);
      expect(valleyMeadowStats.darkFraction).toBeLessThan(0.02);
      // Current: edgeLR 2.95, edgeTB 3.20 vs internal 3.08 (ratio ~1.0x).
      expect(valleyMeadowStats.edgeLR).toBeLessThan(6);
      expect(valleyMeadowStats.edgeTB).toBeLessThan(6);
      expect(valleyMeadowStats.edgeLR / valleyMeadowStats.internal).toBeLessThan(2.5);
      expect(valleyMeadowStats.edgeTB / valleyMeadowStats.internal).toBeLessThan(2.5);
    });

    it("valley path keeps the shared warm-earth average and tiling", () => {
      expect(near(valleyPathStats.avgRGB.r, 170.2, 2)).toBe(true);
      expect(near(valleyPathStats.avgRGB.g, 123.3, 2)).toBe(true);
      expect(near(valleyPathStats.avgRGB.b, 92.7, 2)).toBe(true);
      expect(valleyPathStats.avgHsl.s).toBeGreaterThan(0.30);
      expect(valleyPathStats.avgHsl.s).toBeLessThan(0.40);
      expect(valleyPathStats.edgeLR / valleyPathStats.internal).toBeLessThan(2.2);
      expect(valleyPathStats.edgeTB / valleyPathStats.internal).toBeLessThan(1.8);
    });
  });

  describe("Courier Square plaza (gray-stone cobble, distinct from warm paths)", () => {
    it("keeps the signed-off cool stone average (163, 170, 171)", () => {
      expect(near(plazaStats.avgRGB.r, 163.2, 2)).toBe(true);
      expect(near(plazaStats.avgRGB.g, 170.3, 2)).toBe(true);
      expect(near(plazaStats.avgRGB.b, 171.1, 2)).toBe(true);
    });

    it("stays soft pastel gray (sat ~0.09) — no dark grout grid", () => {
      expect(plazaStats.avgHsl.s).toBeGreaterThan(0.05);
      expect(plazaStats.avgHsl.s).toBeLessThan(0.14);
      expect(plazaStats.darkFraction).toBeLessThan(0.05);
    });

    it("wraps seamlessly — the seam is no worse than internal stone boundaries", () => {
      // Seam (col 0 vs 255) sits inside the range of internal mirror offsets
      // (7.3-12.2); the abs bound guards against a broken wrap like the
      // running-bond attempt that hit edgeTB ~52.
      expect(plazaStats.edgeLR).toBeLessThan(14);
      expect(plazaStats.edgeTB).toBeLessThan(14);
    });
  });
});